name: 'Code Reviewer AI'
description: 'Performs AI-powered code reviews on pull requests'
author: 'orielo'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API key for generating code reviews'
    required: true
  github_token:
    description: 'GitHub token for accessing repository and pull request data'
    required: false
    default: '${{ github.token }}'
  config_path:
    description: 'Path to custom config file (relative to repository root)'
    required: false
    default: '.github/pr_review_config.yml'
  review_mode:
    description: 'Review mode: concise, standard, or thorough'
    required: false
    default: 'standard'
  comment_threshold:
    description: 'Comment threshold: low, medium, or high'
    required: false
    default: 'medium'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: pip install openai==1.3.0 httpx==0.24.1 requests PyGithub==2.1.1 pyyaml==6.0.1
      shell: bash
    
    - name: Run AI Code Review
      run: python ${{ github.action_path }}/src/review_pr.py
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CONFIG_PATH: ${{ inputs.config_path }}
        REVIEW_MODE: ${{ inputs.review_mode }}
        COMMENT_THRESHOLD: ${{ inputs.comment_threshold }} 