# Golden Moth PR Review Configuration
# This file controls the behavior of the AI code reviewer

# Main review settings
review_mode: concise          # Options: concise, standard, thorough
comment_threshold: medium     # Options: low, medium, high

# Define what to focus on
review_focus:
  - bugs
  - security
  - performance
  - maintainability

# File filtering
file_filters:
  include: ["*"]
  exclude: ["*.md", "*.txt", "package-lock.json", "yarn.lock", "*.json", "*.csv", "*.svg"]

# How many words max in the summary
summary_length: 150

# Language-specific settings
language_specific_rules:
  python:
    style_guide: PEP8
    extra_focus: ["type_hints"]
  javascript:
    style_guide: Airbnb
    extra_focus: ["null_safety"] 